import Footer from "@/sections/footer";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '../assets/globals.scss';
import '../assets/mixins.scss';
import Header from "@/sections/header";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
